### ISSUE TITLE
Issues with CreateWand() and AddSpellToWand()

### ISSUE THREAD

**Issue by ghost** [WadeBA/Beefcake#1]
When creating a wand with CreateWand any image I used just wouldn’t show up, the wand would always look like a blue magicians wand and also when using the function AddSpellToWand the permanent argument does nothing and doesn’t add anything.

**Comment by BoldlyGo88** [comment]
I couldn't replicate the problem you were having with the permanent argument as it just worked out of the box for me, however I did find the issue with the graphics not working correctly and it was just me setting the value to the wrong place, as I fixed this I did discover another issue which was the offset of the wand GFX being completely off depending on which image was used so I reworked the CreateWand function to:

**CreateWand(name: string, mana_charge: number, mana_max: number, reload_speed: number, recoil: number, spells_per_shot: int, capacity: int, wand_image: string, offset_x: int, offset_y: int)**

So it now incorporates the wands X and Y offsets to avoid a floating wand when the player is holding it, you may have to tweak these values to get a perfect looking wand.

I tested with this code inside a standard mod init.lua and everything worked correctly, i'll be pushing the update later today.
```lua
function OnPlayerSpawned(player_entity)	
	local x,y = EntityGetTransform(player_entity);
	
	local wand = CreateWand("TEST_WAND", 250, 1000, 0.45, 0.2, 1, 3, "data/items_gfx/wands/wand_0050.png", 8, 4);
	AddSpellToWand(wand, "BLACK_HOLE", true);
	AddSpellToWand(wand, "BOMB_HOLY", false);
	EntitySetTransform(wand, x, y);
	GamePrintImportant("WAND CREATED", tostring(wand));
end;
```

**Which produced this:**
![image](https://github.com/WadeBA/Beefcake/assets/46317043/17896198-2be8-4598-a44a-1eaf6b3bbac5)
